name: flutter_deepar_example
description: Demonstrates the flutter_deepar plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_deepar:
    path: ../

flutter:
  uses-material-design: true
